config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get  "/customer/new", to: "customer#new",    as: :new_customer
  get  "/customer/:id", to: "customer#show",   as: :show_customer
  get "/customer/edit/:id", to: "customer#edit", as: :edit_customer

  post "/customer", to: "customer#create", as: :create_customer
  patch "/customer/:id", to: "customer#update", as: :update_customer

  delete "/customer/:id", to: "customer#destroy", as: :delete_customer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business_type.rb
class BusinessType < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :business_type

  has_many :customer_days, dependent: :destroy
  has_many :days, through: :customer_days


  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "email must exist" }
  validates :phone, presence: true, format: { with: /\A\(?\d{3}\)?[\s\-]?\d{3}\-?\d{4}\z/, message: "must be a valid phone number" }
  validates :city, presence: true
  validates :state, presence: true
  validates :zip_code, length: { in: 5..10 }, presence: true
  validates :days, presence: true

  def next
    Customer.where("id > ?", id).order(:id).first || Customer.order(:id).first
  end

  def previous
    Customer.where("id < ?", id).order(id: :desc).first || Customer.order(id: :desc).first
  end
end

app/models/customer_day.rb
class CustomerDay < ApplicationRecord
  belongs_to :customer
  belongs_to :day
end

app/models/day.rb
class Day < ApplicationRecord
    has_many :customer_days, dependent: :destroy
    has_many :customers, through: :customer_days
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
    # GET /customer/:id
    def show
        @customer = Customer.find_by(id: params[:id])

        if @customer.nil?
            redirect_to root_path, alert: "Customer with id '#{params[:id]}' could not be found."
            return
        end

        # Allows us to link the next page based on id on the page
        @next = @customer.next
        @prev = @customer.previous
    end

    # GET /customer/new
    def new
        @customer = Customer.new
        @business_types = BusinessType.all
        @days = Day.all
    end

    # GET /customer/edit/:id
    def edit
        @customer = Customer.find(params[:id])
        @business_types = BusinessType.all
        @days = Day.all
    end

    # PATCH /customer/:id
    def update
        @customer = Customer.find(params[:id])
        if @customer.update(customer_params)
            redirect_to show_customer_path(@customer), notice: "Customer updated successfully."
        else
            @business_types = BusinessType.all
            @days = Day.all
            render :edit, status: :unprocessable_entity
        end
    end

    # POST /customer
    def create
        @customer = Customer.new(customer_params)
        if @customer.save
            redirect_to root_path, notice: "Customer created successfully."
        else
            @business_types = BusinessType.all
            @days = Day.all
            render :new, status: :unprocessable_entity
        end
    end

    # DELETE /customer/:id
    def destroy
        @customer = Customer.find_by(id: params[:id])
        if @customer.nil?
            redirect_to root_path, alert: "Customer with id '#{params[:id]}' could not be found."
        end

        @customer.destroy

        redirect_to root_path, notice: "Customer successfully deleted."
    end

    private

    # Creates customer from form data
    def customer_params
        params.require(:customer).permit(
        :name, :address1, :address2, :city, :state, :zip_code,
        :email, :phone, :business_type_id, day_ids: []
        )
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @customers = Customer.includes(:business_type, :days).order(created_at: :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def us_states
    [
      [ "Alabama", "AL" ], [ "Alaska", "AK" ], [ "Arizona", "AZ" ], [ "Arkansas", "AR" ], [ "California", "CA" ],
      [ "Colorado", "CO" ], [ "Connecticut", "CT" ], [ "Delaware", "DE" ], [ "Florida", "FL" ], [ "Georgia", "GA" ],
      [ "Hawaii", "HI" ], [ "Idaho", "ID" ], [ "Illinois", "IL" ], [ "Indiana", "IN" ], [ "Iowa", "IA" ],
      [ "Kansas", "KS" ], [ "Kentucky", "KY" ], [ "Louisiana", "LA" ], [ "Maine", "ME" ], [ "Maryland", "MD" ],
      [ "Massachusetts", "MA" ], [ "Michigan", "MI" ], [ "Minnesota", "MN" ], [ "Mississippi", "MS" ], [ "Missouri", "MO" ],
      [ "Montana", "MT" ], [ "Nebraska", "NE" ], [ "Nevada", "NV" ], [ "New Hampshire", "NH" ], [ "New Jersey", "NJ" ],
      [ "New Mexico", "NM" ], [ "New York", "NY" ], [ "North Carolina", "NC" ], [ "North Dakota", "ND" ], [ "Ohio", "OH" ],
      [ "Oklahoma", "OK" ], [ "Oregon", "OR" ], [ "Pennsylvania", "PA" ], [ "Rhode Island", "RI" ], [ "South Carolina", "SC" ],
      [ "South Dakota", "SD" ], [ "Tennessee", "TN" ], [ "Texas", "TX" ], [ "Utah", "UT" ], [ "Vermont", "VT" ],
      [ "Virginia", "VA" ], [ "Washington", "WA" ], [ "West Virginia", "WV" ], [ "Wisconsin", "WI" ], [ "Wyoming", "WY" ]
    ]
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/customer/_form.html.erb
<%= form_with model: @customer, url: @customer.persisted? ? update_customer_path(@customer) : create_customer_path, method: @customer.persisted? ? :patch : :post, local: true do |f| %>
        <div class="mb-3 row">
            <div class="col-12 col-sm-7">
                <%= f.label :name, "Customer Name" %>
                <%= f.text_field :name, class: "form-control" %>
                <% @customer.errors[:name].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        Name <%= msg %>
                    </div>
                <% end %>
            </div>

            <div class="col-12 col-sm-5">
                <%= f.label :business_type_id, "Type of Business" %>
                <%= f.collection_select :business_type_id, @business_types, :id, :name, { prompt: "Select Type" }, class: "form-select" %>
                <% @customer.errors[:business_type].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        Business Type <%= msg %>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :address1, "Address Line 1" %>
                <%= f.text_field :address1, class: "form-control", placeholder: "Address Line 1" %>
                <% @customer.errors[:address1].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        Address <%= msg %>
                    </div>
                <% end %>
            </div>
            <div class="col-6">
                <%= f.label :address2, "Address Line 2" %>
                <%= f.text_field :address2, class: "form-control", placeholder: "Address Line 2" %>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-sm-5 col-12">
                <%= f.label :city %>
                <%= f.text_field :city, class: "form-control" %>
                <% @customer.errors[:city].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        City <%= msg %>
                    </div>
                <% end %>
            </div>

            <div class="col-sm-4 col-12">
                <%= f.label :state %>
                <%= f.select :state, us_states, { prompt: "Select a state" }, class: "form-select" %>
                <% @customer.errors[:state].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        State <%= msg %>
                    </div>
                <% end %>
            </div>

            <div class="col-sm-3 col-12">
                <%= f.label :zip_code %>
                <%= f.text_field :zip_code, class: "form-control", maxlength: 10 %>
                <% @customer.errors[:zip_code].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        Zip code <%= msg %>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="mb-3 row">
            <div class="col-6">
                <%= f.label :phone %>
                <%= f.telephone_field :phone, class: "form-control" %>
                <% @customer.errors[:phone].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        Phone <%= msg %>
                    </div>
                <% end %>
            </div>

            <div class="col-6">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control" %>
                <% @customer.errors[:email].each do |msg| %>
                    <div class="invalid-feedback d-block mb-0">
                        Email <%= msg %>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="mb-3">
            <p>Preferred Days of Receiving Shipments:</p>
            <div class="btn-group" role="group" aria-label="Days of Week">
                <% @days.each do |day| %>
                    <%= check_box_tag "customer[day_ids][]", day.id, @customer.day_ids.include?(day.id),
                        id: "day_#{day.id}",
                        class: "btn-check",
                        autocomplete: "off" %>
                    <%= label_tag "day_#{day.id}", day.name, class: "btn btn-outline-success" %>
                <% end %>
            </div>
            <% if @customer.errors[:days].any? %>
                <div class="invalid-feedback d-block">
                    Please select a day.
                </div>
            <% end %>
        </div>

        <%= f.submit @customer.persisted? ? "Update" : "Submit", class: "btn btn-primary" %>
    <% end %>

app/views/customer/edit.html.erb
<h2>Edit Customer Information</h2>
<%= render 'form' %>  

app/views/customer/new.html.erb
<h2>Customer Information Form</h2>
<%= render 'form' %>   

app/views/customer/show.html.erb
<div class="d-flex justify-content-between align-items-center mb-0 ms-2">
  <h2 class="mb-0"><%= @customer.name %></h2>
  
  <div class="d-flex gap-2 mb-0">
    <%= button_to edit_customer_path(@customer), method: :get, 
      class: "btn btn-outline-primary shadow d-flex align-items-center gap-2 px-3 py-1", 
      form: { class: "d-inline"} do %>
      <strong class="d-none d-sm-inline">Edit</strong>
      <i class="fa-solid fa-pencil"></i>
    <% end %>
    <%= button_to delete_customer_path(@customer), method: :delete, 
      class: "btn btn-outline-danger shadow d-flex align-items-center gap-2 px-3 py-1", 
      form: { class: "d-inline", data: { turbo_confirm: "Are you sure?" } } do %>
      <strong class="d-none d-sm-inline">Delete</strong>
      <i class="fa-solid fa-trash-can"></i>
    <% end %>
  </div>
</div>
<p class="mb-0 text-muted ms-2"><strong><%= @customer.business_type.name %></strong></p>
<p class="text-muted small mb-2 ms-2">
    Added on <%= @customer.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%b %-d, %Y %l:%M %p") %>
</p>
<div class="row">
  <div class="col-12 col-sm-6 mb-3">
    <div class="card p-3 pt-2 shadow h-100">
      <div class="mb-2">
          <p class="mb-0"><%= @customer.address1 %></p>
          <% if @customer.address2.present? %>
              <p class="mb-0"><%= @customer.address2 %></p>
          <% end %>
          <p class="mb-0"><%= @customer.city %>, <%= @customer.state %> <%= @customer.zip_code %></p>
      </div>
    

      <div> <!-- Days Available -->
          <span><strong>Days: </strong></span>
          <% @customer.days.each do |day| %>
              <span class="badge bg-success me-1"><%= day.name_short %></span>
          <% end %>
      </div>
    </div>
  </div>

  <div class="col-12 col-sm-6 mb-3">
    <div class="card p-3 pt-2 shadow h-100">
          <p class="mb-1"><strong>Contact Information:</strong></p>
          <p class="mb-0"><strong>Email: </strong><%= @customer.email %></p>
          <p class="mb-0"><strong>Phone: </strong><%= @customer.phone %></p>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center mt-3 gap-5">
  <%= link_to show_customer_path(@prev), class: "btn btn-outline-secondary shadow d-flex align-items-center justify-content-center", style: "width: 2rem; height: 2rem;" do %>
    <i class="fa-solid fa-chevron-left fs-4"></i>
  <% end %>

  <%= link_to show_customer_path(@next), class: "btn btn-outline-secondary shadow d-flex align-items-center justify-content-center", style: "width: 2rem; height: 2rem;" do %>
    <i class="fa-solid fa-chevron-right fs-4"></i>
  <% end %>
</div>

app/views/home/index.html.erb
<div id="index">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h2 class="mb-0">All Customers</h2>

    
  </div>
  <div class="table-container rounded border shadow-sm overflow-hidden">
    <div class="table-responsive">
      <table id="customer-table" class="table table-sm table-hover table-striped align-middle mb-0">
        <thead class="table-light">
          <tr>
            <th>Name</th>
            <th>Business Type</th>
            <th>State</th>
            <th>Days</th>
            <th>Added</th>
            <th class="text-end no-sort" data-sort-method="none">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td class="text-nowrap">
                <%= link_to customer.name, show_customer_path(customer) %>
              </td>
              <td class="text-nowrap"><%= customer.business_type.name %></td>
              <td><%= customer.state %></td>
              <td class="text-nowrap">
                <% customer.days.each do |day| %>
                  <span class="badge bg-success me-1"><%= day.name_short %></span>
                <% end %>
              </td>
              <td class="text-nowrap text-muted small">
                <%= customer.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%b %-d, %Y %l:%M %p") %>
              </td>
              <td class="text-end">
                <%= button_to edit_customer_path(customer), method: :get, 
                  class: "btn btn-sm btn-outline-primary", 
                  form: { class: "d-inline"} do %>
                  <i class="fa-solid fa-pencil"></i>
                <% end %>
                <%= button_to delete_customer_path(customer), method: :delete, 
                  class: "btn btn-sm btn-outline-danger", 
                  form: { class: "d-inline", data: { turbo_confirm: "Are you sure?" } } do %>
                  <i class="fa-solid fa-trash-can"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Assessment Project" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.6.0/css/all.css" integrity="sha384-h/hnnw1Bi4nbpD6kE7nYfCXzovi622sY5WBxww8ARKwpdLj5kUWjRuyiXaD1U2JT" crossorigin="anonymous" />
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-1">
      <div class="container-fluid d-flex justify-content-between align-items-center">
        <%= link_to "Assessment Project", root_path, class: "navbar-brand mb-0" %>

        <%= button_to new_customer_path, method: :get, 
          class: "btn btn-primary shadow d-flex align-items-center gap-2 px-3 py-1", 
          form: { class: "d-inline" } do %>
          <strong class="d-none d-sm-inline">Add Customer</strong>
          <i class="fa-solid fa-plus"></i>
        <% end %>
      </div>
    </nav>
    <div class="container mt-3">
      <% if flash[:notice] %>
        <div class="alert alert-primary alert-dismissible fade show mb-2" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible fade show mb-2" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2/dist/umd/popper.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
</html>